version: "3.1"

services:
  node-fizz:
    #build: 
    #  context: ./
    #  dockerfile: dockerfile
    image: node-fizz:1.0
    ports:
        - 8000:8000
    healthcheck:
        test: ["CMD", "wget", "-csq", "http://localhost:8080"]
        interval: 1m
        timeout: 10s
        retries: 3